import os
import copy

import torch
import numpy as np
import mdtraj as md
import pandas as pd
from sklearn.cluster import DBSCAN, AgglomerativeClustering
from Bio.PDB import PDBParser

from utils.rewarder import Rewarder

# ============================================================
# Basic sequence encoding utilities (adapted from AF_Cluster)
# ============================================================

ALPHABET = "ACDEFGHIKLMNPQRSTVWY-"
ALPHABET_DICT = {res: i for i, res in enumerate(ALPHABET)}
NUM_TOKENS = len(ALPHABET)


def encode_seqs(seqs, max_len=108, alphabet=None):
    """
    One-hot encode a list of sequences into a flattened array.

    Args:
        seqs: List[str], sequences (upper-case residues and '-' gaps).
        max_len: int, maximum sequence length used for encoding.
        alphabet: str, alphabet characters used for encoding.

    Returns:
        np.ndarray of shape [N, max_len * len(alphabet)]
    """
    if alphabet is None:
        alphabet = ALPHABET

    arr = np.zeros([len(seqs), max_len, len(alphabet)], dtype=np.float32)
    for j, seq in enumerate(seqs):
        for i, char in enumerate(seq):
            for k, res in enumerate(alphabet):
                if char == res:
                    arr[j, i, k] += 1.0
    return arr.reshape([len(seqs), max_len * len(alphabet)])


def generate_embed(a3m_path, embed_path):
    """
    Build simple one-hot embeddings for sequences in an A3M file and save as .npy.

    Important:
        This function expects `a3m_path` to be the cleaned A3M generated by `clean_msa`,
        i.e., it should contain ONLY target (header, sequence) pairs (no query pair).

    Args:
        a3m_path: str, cleaned A3M path containing target pairs only.
        embed_path: str, output path to save embeddings (.npy).
    """
    with open(a3m_path, "r") as f:
        lines = f.readlines()

    # lines: [header0, seq0, header1, seq1, ...]
    seqs = lines[1::2]
    seqs = ["".join([x for x in s if x.isupper() or x == "-"]) for s in seqs]

    embed = encode_seqs(seqs, max_len=len(seqs[0]))
    np.save(embed_path, embed)


# ============================================================
# TaxID parsing and taxonomy-distance clustering
# ============================================================

def get_taxID(a3m_path, valid_taxid_set):
    """
    Parse a cleaned A3M file (targets only) and split indices into:
      - tax-valid: header contains TaxID=..., and TaxID is in valid_taxid_set
      - orphan: missing TaxID, or TaxID not in valid_taxid_set, or malformed TaxID

    Args:
        a3m_path: str, cleaned A3M path containing ONLY target pairs.
        valid_taxid_set: set[int], allowed TaxIDs (e.g., set(tax_df.index))

    Returns:
        tax_ids: List[int], TaxIDs for tax-valid targets (same order as tax_valid_idx)
        lines_all: np.ndarray, shape [N_targets, 2], (header, sequence) pairs
        tax_valid_idx: np.ndarray[int], indices into lines_all for tax-valid targets
        orphan_idx: np.ndarray[int], indices into lines_all for orphan targets
    """
    with open(a3m_path, "r") as f:
        lines = f.readlines()

    lines_all = np.array(lines).reshape(-1, 2)

    tax_ids = []
    tax_valid_idx = []
    orphan_idx = []

    for i, pair in enumerate(lines_all):
        header = pair[0]
        if "TaxID=" in header:
            tax = header.split("TaxID=")[-1].split()[0]
            if str(tax).isdigit() and int(tax) in valid_taxid_set:
                tax_ids.append(int(tax))
                tax_valid_idx.append(i)
            else:
                orphan_idx.append(i)
        else:
            orphan_idx.append(i)

    return (
        tax_ids,
        lines_all,
        np.array(tax_valid_idx, dtype=int),
        np.array(orphan_idx, dtype=int),
    )


def calculate_tax_distance(tax_df, tax_ids):
    """
    Compute a discrete taxonomy distance matrix based on lineage similarity.

    Args:
        tax_df: pd.DataFrame indexed by TaxID. Columns represent ranks.
        tax_ids: List[int], TaxIDs to compare

    Returns:
        np.ndarray of shape [N, N], distances in [0..8]
    """
    nums = len(tax_ids)
    dist_matrix = np.zeros((nums, nums), dtype=np.float32)

    for i in range(nums):
        compare = tax_df.loc[tax_ids[i]] == tax_df.loc[tax_ids]
        # Legacy trick to handle identical lineages consistently
        compare.insert(loc=0, column="overkingdom", value=True)
        compare.insert(loc=8, column="completesame", value=False)
        dist = 8 - (~compare).to_numpy().astype(int).argmax(axis=1)
        dist_matrix[i] = dist

    np.fill_diagonal(dist_matrix, 0.0)
    return dist_matrix


def cluster_analysis(
    name,
    level,
    tax_df,
    output_dir,
    fasta_path,
    a3m_path,          # IMPORTANT: this should be the cleaned A3M path (targets only)
    embed_path,
    fasta_dir_for_openfold,
    orphan_dir,
    min_cluster_size=5,
):
    """
    Two-stage clustering with orphan handling.

    Policy:
      - Sequences with missing/invalid TaxID => orphan pool
      - Taxonomy clustering (Agglomerative) is applied to valid-tax sequences
      - Any taxonomy cluster with size < min_cluster_size => moved to orphan pool
      - For each large taxonomy cluster, DBSCAN is applied to embeddings to form subclusters
          * DBSCAN noise (-1) => orphan pool
          * Any subcluster with size < min_cluster_size => orphan pool
      - Finally, the union orphan pool is clustered by DBSCAN and exported.

    Outputs:
      - fasta_dir_for_openfold/*.a3m : non-orphan tax-subclusters
      - orphan_dir/*.a3m            : orphan clusters
      - output_dir/data_info.csv    : bookkeeping table
      - output_dir/dist_matrix.npy  : taxonomy distance matrix (valid-tax subset only; for inspection)

    Args:
        name: str, target name
        level: float/int, taxonomy distance threshold control (your original setting)
        tax_df: taxonomy lineage table indexed by TaxID
        output_dir: str
        fasta_path: str, query fasta file path (used to prepend query into exported A3Ms)
        a3m_path: str, cleaned A3M containing target pairs only
        embed_path: str, embeddings from generate_embed(a3m_path)
        fasta_dir_for_openfold: str, output dir for non-orphan clusters
        orphan_dir: str, output dir for orphan clusters
        min_cluster_size: int, minimum size to keep a cluster as non-orphan
    """
    emb = np.load(embed_path)  # [N_targets, L*21]
    prot_length = emb.shape[-1] // 21

    with open(fasta_path, "r") as ff:
        fasta_lines = ff.readlines()[1]  # query sequence line

    # Split sequences into (valid-tax) and (orphan base)
    valid_taxid_set = set(tax_df.index)
    tax_ids, lines_all, tax_valid_idx, orphan_idx_base = get_taxID(a3m_path, valid_taxid_set)

    # Bookkeeping
    data_info = pd.DataFrame({"embed_idx": np.arange(emb.shape[0])})
    data_info["label"] = -1
    data_info["sub_label"] = -1
    data_info["is_orphan"] = True

    orphan_set = set(orphan_idx_base.tolist())

    # ---------- 1) Taxonomy clustering on valid-tax subset ----------
    if len(tax_valid_idx) >= 2:
        dist_matrix = calculate_tax_distance(tax_df, tax_ids)  # [N_valid, N_valid]
        np.save(os.path.join(output_dir, "dist_matrix.npy"), dist_matrix)

        level_eff = float(level) + 0.5
        tax_cluster = AgglomerativeClustering(
            n_clusters=None,
            metric="precomputed",
            linkage="complete",
            distance_threshold=level_eff,
        )
        labels_valid = tax_cluster.fit_predict(dist_matrix)  # length N_valid

        # Write back tax labels to global indices
        data_info.loc[tax_valid_idx, "label"] = labels_valid

        # Determine large taxonomy clusters (>= min_cluster_size)
        unique_labels, counts = np.unique(labels_valid, return_counts=True)
        large_tax_labels = set([lab for lab, cnt in zip(unique_labels, counts) if cnt >= min_cluster_size])

        # Valid-tax but small tax cluster => orphan
        for local_i, gidx in enumerate(tax_valid_idx):
            if labels_valid[local_i] not in large_tax_labels:
                orphan_set.add(int(gidx))

        # ---------- 2) DBSCAN subclustering inside each large taxonomy cluster ----------
        eps_test_vals = np.arange(3, max(prot_length // 10, 4), 1)
        if len(eps_test_vals) == 0:
            eps_test_vals = np.array([3])

        for tax_lab in sorted(list(large_tax_labels)):
            local_members = np.where(labels_valid == tax_lab)[0]      # indices in valid-subset
            global_members = tax_valid_idx[local_members]             # indices in emb/lines_all

            sub_emb = emb[global_members]

            # Heuristic: choose eps that maximizes number of clusters
            n_clusters_list = []
            for eps in eps_test_vals:
                clustering_db = DBSCAN(eps=float(eps), min_samples=min_cluster_size).fit(sub_emb)
                n_clusters_list.append(len(set(clustering_db.labels_)))

            eps_to_select = eps_test_vals[int(np.argmax(n_clusters_list))]
            sub_dbscan = DBSCAN(eps=float(eps_to_select), min_samples=min_cluster_size).fit(sub_emb)
            sub_labels = sub_dbscan.labels_

            data_info.loc[global_members, "sub_label"] = sub_labels

            # Export each valid subcluster; move noise/small groups to orphan
            for sub_lab in set(sub_labels.tolist()):
                sub_mask = np.where(sub_labels == sub_lab)[0]
                sub_global_idx = global_members[sub_mask]

                if sub_lab == -1:
                    for gi in sub_global_idx.tolist():
                        orphan_set.add(int(gi))
                    continue

                if len(sub_global_idx) < min_cluster_size:
                    for gi in sub_global_idx.tolist():
                        orphan_set.add(int(gi))
                    continue

                filename = f"{name}_{tax_lab}_{sub_lab}"
                saved_lines = lines_all[sub_global_idx].reshape(-1).tolist()

                with open(os.path.join(fasta_dir_for_openfold, f"{filename}.a3m"), "w") as fa:
                    fa.writelines([f">{filename}\n"])
                    fa.writelines(fasta_lines)
                    if "\n" not in fasta_lines:
                        fa.writelines(["\n"])
                    fa.writelines(saved_lines)

                data_info.loc[sub_global_idx, "is_orphan"] = False

    else:
        # Not enough valid-tax sequences => treat all as orphan
        if len(tax_valid_idx) > 0:
            orphan_set.update([int(x) for x in tax_valid_idx.tolist()])

    # ---------- 3) Orphan clustering (union orphan set) ----------
    orphan_idx = np.array(sorted(list(orphan_set)), dtype=int)

    if len(orphan_idx) > 0:
        emb_orphans = emb[orphan_idx]

        eps_test_vals = np.arange(3, max(prot_length // 10, 4), 0.5)
        if len(eps_test_vals) == 0:
            eps_test_vals = np.array([3.0])

        n_clusters_list = []
        for eps in eps_test_vals:
            clustering_db = DBSCAN(eps=float(eps), min_samples=min_cluster_size).fit(emb_orphans)
            n_clusters_list.append(len(set(clustering_db.labels_)))

        eps_to_select = eps_test_vals[int(np.argmax(n_clusters_list))]
        orphan_dbscan = DBSCAN(eps=float(eps_to_select), min_samples=min_cluster_size).fit(emb_orphans)
        orphan_labels = orphan_dbscan.labels_

        for orphan_lab in set(orphan_labels.tolist()):
            if orphan_lab == -1:
                continue

            members = orphan_idx[np.where(orphan_labels == orphan_lab)[0]]
            if len(members) < min_cluster_size:
                continue

            filename = f"{name}_orphan_{orphan_lab}"
            saved_lines = lines_all[members].reshape(-1).tolist()

            with open(os.path.join(orphan_dir, f"{filename}.a3m"), "w") as fa:
                fa.writelines([f">{filename}\n"])
                fa.writelines(fasta_lines)
                if "\n" not in fasta_lines:
                    fa.writelines(["\n"])
                fa.writelines(saved_lines)

    data_info.to_csv(os.path.join(output_dir, "data_info.csv"), index=False)
    return data_info


# ============================================================
# MSA cleaning: keep valid TaxID sequences AND orphans
# ============================================================

def clean_msa(
    raw_a3m_path,
    clean_a3m_path,
    valid_taxid_set,
    max_valid_tax=10000,
    max_orphan=None,
):
    """
    Create a cleaned A3M file (targets only) by keeping:
      - valid-tax sequences (TaxID in valid_taxid_set), capped by max_valid_tax
      - orphan sequences (missing/invalid TaxID), optionally capped by max_orphan

    IMPORTANT:
        This function writes ONLY target pairs (no query pair).
        The query sequence will be re-added when exporting cluster A3Ms.

    Args:
        raw_a3m_path: str, original A3M containing query + targets
        clean_a3m_path: str, output cleaned A3M path (targets only)
        valid_taxid_set: set[int], allowed TaxIDs
        max_valid_tax: int or None
        max_orphan: int or None
    """
    with open(raw_a3m_path, "r") as f:
        lines = f.readlines()

    pairs = np.array(lines).reshape(-1, 2)
    target_pairs = pairs[1:]  # skip query pair

    valid_pairs = []
    orphan_pairs = []

    for pair in target_pairs:
        header = pair[0]
        is_valid = False

        if "TaxID=" in header:
            taxid = header.split("TaxID=")[-1].split()[0]
            if str(taxid).isdigit() and int(taxid) in valid_taxid_set:
                is_valid = True

        if is_valid:
            valid_pairs.append(pair)
        else:
            orphan_pairs.append(pair)

    if max_valid_tax is not None and len(valid_pairs) > max_valid_tax:
        valid_pairs = valid_pairs[:max_valid_tax]

    if max_orphan is not None and len(orphan_pairs) > max_orphan:
        orphan_pairs = orphan_pairs[:max_orphan]

    out_pairs = valid_pairs + orphan_pairs
    out_lines = np.array(out_pairs).reshape(-1).tolist() if len(out_pairs) > 0 else []

    with open(clean_a3m_path, "w") as fw:
        fw.writelines(out_lines)


# ============================================================
# RL helpers (kept as-is)
# ============================================================

def replace_check(scores, rmsd_threshold):
    mask = scores < rmsd_threshold
    indices = torch.nonzero(mask, as_tuple=False).squeeze()
    if indices.numel() == 1:
        return indices.item()
    else:
        return False


def share_buffer(envs, rewarder, num_buffer, rmsd_threshold):
    buffer_pool = envs[0].buffer[:num_buffer].copy()
    new_num_buffer = num_buffer
    for env in envs:
        if len(env.buffer) > num_buffer:
            for _, frame in env.buffer[num_buffer:].iterrows():
                if len(buffer_pool) > 0:
                    scores = rewarder.calculate(frame["structure"], np.stack(buffer_pool["structure"]))
                    score = scores.min().item()
                    if score > rmsd_threshold:
                        buffer_pool = pd.concat([buffer_pool, frame.to_frame().T], ignore_index=True)
                        new_num_buffer += 1
                else:
                    buffer_pool = pd.concat([buffer_pool, frame.to_frame().T], ignore_index=True)
                    new_num_buffer += 1
    return buffer_pool, new_num_buffer


def shifted_tanh(x, threshold, sharpness=1.0):
    return torch.tanh((x - threshold) * sharpness)


def encode_batch_msa(msa_list):
    """
    Encode a batch of MSAs:
      - one-hot each sequence (L x 21),
      - flatten to (L*21),
      - average over sequences within each MSA.

    Args:
        msa_list: List[List[str]], each inner list contains sequences only (no headers).

    Returns:
        torch.Tensor of shape [batch, L*21]
    """
    seq_counts = [len(msa) for msa in msa_list]
    max_len = len(msa_list[0][0])

    total_seqs = sum(seq_counts)
    arr = np.full((total_seqs, max_len), fill_value=ALPHABET_DICT["-"], dtype=np.int64)

    offset = 0
    for msa in msa_list:
        for seq in msa:
            for j, char in enumerate(seq):
                if char in ALPHABET_DICT:
                    arr[offset, j] = ALPHABET_DICT[char]
            offset += 1

    one_hot = np.eye(NUM_TOKENS, dtype=np.float32)[arr]
    one_hot = one_hot.reshape(total_seqs, -1)

    embeddings = []
    offset = 0
    for count in seq_counts:
        emb = torch.tensor(one_hot[offset:offset + count]).mean(dim=0)
        embeddings.append(emb)
        offset += count

    return torch.stack(embeddings)


def get_all_hypo_embeddings(env):
    base = clean_sequences(env.msa)
    msa_list = []
    for cluster in env.availables:
        combined = base + cluster
        msa_list.append(clean_sequences(combined))
    return encode_batch_msa(msa_list)


def clean_sequences(seq_list):
    cleaned = []
    for line in seq_list:
        if line.startswith(">"):
            continue
        cleaned.append("".join(c for c in line.strip() if c.isupper() or c == "-"))
    return cleaned


# ============================================================
# PDB utilities
# ============================================================

def extract_ca_bfactors(pdb_file):
    """
    Extract B-factors for all C-alpha atoms in a PDB file.
    In AlphaFold/OpenFold outputs, C-alpha B-factors typically store pLDDT scores.
    """
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure("structure", pdb_file)

    ca_bfactors = []
    for model in structure:
        for chain in model:
            for residue in chain:
                if "CA" in residue.child_dict:
                    ca_atom = residue["CA"]
                    ca_bfactors.append(ca_atom.get_bfactor())
    return ca_bfactors


def prepare_init_data(init_dir, pdb_list, clusters, plddt_threshold, rmsd_matrix):
    """
    Select initial seed indices by:
      - filtering by mean pLDDT
      - clustering with RMSD threshold
      - taking highest pLDDT representative per cluster

    Output:
        init_idx.npy under init_dir
    """
    traj = md.load(copy.copy(pdb_list))

    # Compute mean pLDDT for each structure
    plddts = []
    for fp in pdb_list:
        p = extract_ca_bfactors(fp)
        plddts.append(p)
    plddts = (np.stack(plddts) / 100.0).mean(axis=-1)

    filted_idx = np.where(plddts > plddt_threshold)[0]

    rmsds = rmsd_matrix[filted_idx, :][:, filted_idx].numpy()

    rmsd_threshold = 0.28 * np.sqrt(traj.top.n_residues)
    if len(rmsds) >= 2:
        cluster = AgglomerativeClustering(
            n_clusters=None,
            metric="precomputed",
            linkage="complete",
            distance_threshold=rmsd_threshold,
        )
        labels = cluster.fit_predict(rmsds)
    else:
        labels = np.array([0])

    non_redundant_idx = []
    for label in range(labels.max() + 1):
        label_idx = np.where(labels == label)[0]
        if len(label_idx) <= 1:
            continue
        plddts_label = plddts[filted_idx][label_idx]
        non_redundant_idx.append(filted_idx[label_idx[np.argmax(plddts_label)]])

    init_idx = np.array(non_redundant_idx).astype(int)
    np.save(os.path.join(init_dir, "init_idx.npy"), init_idx)
